(() => {
  const client = () => window.supabaseClient;
  const message = (text,type='info') => { const n=document.getElementById('auth-message'); if(!n)return; n.textContent=text; n.dataset.type=type; n.hidden=false; };
  const setLoading = (form,loading) => { const b=form?.querySelector('button[type="submit"]'); if(!b)return; b.disabled=loading; b.dataset.originalText ||= b.textContent; b.textContent=loading?'Aguarde...':b.dataset.originalText; };
  async function getSession(){ const {data,error}=await client().auth.getUser(); if(error){console.error(error);return null;} return data.user?{user:data.user}:null; }
  async function getAppRole(userId){ if(!userId)return 'customer'; const r=await client().from('profiles').select('role').eq('id',userId).maybeSingle(); return !r.error&&r.data?.role?r.data.role:'customer'; }
  async function getProfile(userId){ const {data,error}=await client().from('profiles').select('id,full_name,phone,company,address,avatar_url,role,created_at,updated_at').eq('id',userId).maybeSingle(); if(error)throw error; return data; }
  async function requireSession(){const s=await getSession();if(!s){window.location.href='auth.html';return null;}return s;}
  function consumeAuthReturn(){const raw=sessionStorage.getItem('mukwatela-auth-return');sessionStorage.removeItem('mukwatela-auth-return');if(!raw||!raw.startsWith('/')||raw.startsWith('//'))return null;try{const u=new URL(raw,location.origin);if(u.origin!==location.origin||['/auth.html','/register.html','/recuperar-password.html'].includes(u.pathname))return null;return u.pathname+u.search+u.hash;}catch(_){return null;}}
  async function redirectByRole(session,{allowPendingCheckout=false}={}){if(!session?.user?.id){location.href='auth.html';return true;}const role=await getAppRole(session.user.id);const ret=consumeAuthReturn();if(role==='admin'){location.href='admin.html';return true;}if(ret){location.href=ret;return true;}if(allowPendingCheckout&&sessionStorage.getItem('mukwatela-selected-service-id')){location.href='checkout.html';return true;}location.href='dashboard.html';return true;}
  async function initLogin(){const form=document.getElementById('login-form');if(!form)return;const s=await getSession();if(s){await redirectByRole(s,{allowPendingCheckout:true});return;}form.addEventListener('submit',async e=>{e.preventDefault();setLoading(form,true);const {data,error}=await client().auth.signInWithPassword({email:form.elements.email.value.trim(),password:form.elements.password.value});if(error){message(error.message==='Email not confirmed'?'Confirme o seu email antes de entrar.':'Email ou palavra-passe incorretos.','error');setLoading(form,false);return;}if(data.session)await redirectByRole(data.session,{allowPendingCheckout:true});});document.getElementById('forgot-password-btn')?.addEventListener('click',async()=>{const email=form.elements.email.value.trim();if(!email){message('Digite o seu email primeiro.','error');return;}const b=document.getElementById('forgot-password-btn');b.disabled=true;const recoveryUrl=new URL('recuperar-password.html',location.href).href;const {error}=await client().auth.resetPasswordForEmail(email,{redirectTo:recoveryUrl});message(error?'Não foi possível enviar o email de recuperação.':'Enviámos um link de recuperação para o seu email.',error?'error':'success');b.disabled=false;});}
  async function initRegister(){const form=document.getElementById('register-form');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();setLoading(form,true);const name=form.elements.name.value.trim(),company=form.elements.company.value.trim(),email=form.elements.email.value.trim(),phone=form.elements.phone.value.trim(),password=form.elements.password.value,confirmPassword=form.elements.confirmPassword.value;if(password!==confirmPassword){message('As palavras-passe não coincidem.','error');setLoading(form,false);return;}if(password.length<6){message('A palavra-passe deve ter pelo menos 6 caracteres.','error');setLoading(form,false);return;}const {data,error}=await client().auth.signUp({email,password,options:{data:{full_name:name,phone,company},emailRedirectTo:new URL('confirmacao.html',location.origin).href}});if(error){message(error.message||'Não foi possível criar a conta.','error');setLoading(form,false);return;}if(data.session){await redirectByRole(data.session);return;}message('Conta criada. Enviámos um email de confirmação. Abra o email e clique em “Confirmar conta”.','success');form.reset();setLoading(form,false);});}
  async function initDashboard(){const s=await requireSession();if(!s)return;if(await getAppRole(s.user.id)==='admin'){location.href='admin.html';return;}try{const p=await getProfile(s.user.id);const name=p?.full_name||s.user.email?.split('@')[0]||'Cliente';document.getElementById('user-name')?.replaceChildren(document.createTextNode(name));document.getElementById('user-avatar')?.replaceChildren(document.createTextNode(name.trim().charAt(0).toUpperCase()||'C'));document.getElementById('user-email')?.replaceChildren(document.createTextNode(s.user.email||''));document.getElementById('user-role')?.replaceChildren(document.createTextNode('Cliente'));}catch(e){console.error(e);document.getElementById('user-name')?.replaceChildren(document.createTextNode(s.user.email||'Cliente'));}}
  async function initProfile(){const s=await requireSession();if(!s)return;if(await getAppRole(s.user.id)==='admin'){location.href='admin.html';return;}const form=document.getElementById('profile-form');if(!form)return;try{const p=await getProfile(s.user.id);if(!p){message('Perfil não encontrado.','error');return;}form.elements.name.value=p.full_name||'';if(form.elements.company)form.elements.company.value=p.company||'';form.elements.email.value=s.user.email||'';form.elements.email.readOnly=true;form.elements.phone.value=p.phone||'';if(form.elements.address)form.elements.address.value=p.address||'';form.addEventListener('submit',async e=>{e.preventDefault();setLoading(form,true);const patch={full_name:form.elements.name.value.trim(),phone:form.elements.phone.value.trim(),updated_at:new Date().toISOString()};if(form.elements.company)patch.company=form.elements.company.value.trim();if(form.elements.address)patch.address=form.elements.address.value.trim();const {error}=await client().from('profiles').update(patch).eq('id',s.user.id);message(error?'Não foi possível guardar as alterações.':'Perfil atualizado com sucesso.',error?'error':'success');setLoading(form,false);});}catch(e){console.error(e);message('Não foi possível carregar o seu perfil.','error');}}
  async function initRecovery(){const form=document.getElementById('recovery-form');if(!form)return;const b=form.querySelector('button[type="submit"]');if(b)b.disabled=true;let recoverySession=window.mukwatelaAuthState?.recoverySession||null;if(!recoverySession){const {data}=await client().auth.getSession();recoverySession=data?.session||null;}if(!recoverySession){message('Este link de recuperação não abriu uma sessão válida. Solicite um novo link.','error');return;}if(b)b.disabled=false;message('Link de recuperação validado. Escolha a sua nova palavra-passe.','success');form.addEventListener('submit',async e=>{e.preventDefault();setLoading(form,true);const password=form.elements.password.value,confirmPassword=form.elements.confirmPassword.value;if(password!==confirmPassword||password.length<6){message(password!==confirmPassword?'As palavras-passe não coincidem.':'A palavra-passe deve ter pelo menos 6 caracteres.','error');setLoading(form,false);return;}const {error}=await client().auth.updateUser({password});if(error){message('Não foi possível atualizar a palavra-passe.','error');setLoading(form,false);return;}message('Palavra-passe atualizada com sucesso.','success');form.reset();setTimeout(()=>location.href='auth.html',1000);});}
  async function initLogout(){document.querySelectorAll('[data-logout]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;await client().auth.signOut();location.href='auth.html';}));}
  async function init(){if(!client())return;const page=document.body.dataset.page;if(page==='auth')await initLogin();if(page==='register')await initRegister();if(page==='dashboard')await initDashboard();if(page==='profile')await initProfile();if(page==='recovery')await initRecovery();await initLogout();}
  document.addEventListener('DOMContentLoaded',init);
})();